Refactoring global logger
davidjurgens/potato pull request #16
Opened 2022-11-21 22:38 UTC by ajyl

2022-11-21 23:01 UTC, davidjurgens requested changes

2022-11-21 23:19 UTC, ajyl commented on potato/flask_server.py
> +
Hmm, I thought I had removed this -- removing now...

2022-11-21 23:43 UTC, ajyl commented on potato/server_utils/logger.py
> +    logger = logging.getLogger(logger_name)
Hmm, the nice thing about `config` was that we're calling `config.update()`, such that when `init_config()` is being called, the global variable was being updated.

With `logger`, the issue I'm running into is as following:

1) `logger` is initialized as a global variable with something like `logger = None`
2) In `flask_server.py`, we do `import logger`. Note that at this point, `logger` is None.
3) Eventually, `init_logger()` is called, but unlike our `config`, which is updating our `config` variable, this line does not update `logger` for us.
4) This is a problem `logger` in `flask_server.py` stays as `None` despite calling `init_logger()`.

I agree that a solution like the one we had for `config` would be nicer. Furthermore, previously, my understanding is that a single logger instance is being created by `config["logger_name"]` -- having a dependency on this config value makes it a bit trickier to refactor. Any thoughts on removing such dependency and just using module names? https://stackoverflow.com/questions/15727420/using-logging-in-multiple-modules

2022-11-21 23:56 UTC, davidjurgens commented on potato/server_utils/logger.py
> +    logger = logging.getLogger(logger_name)
Hmm... I see the issue now. How about we merge this one so it Just Works™ for now and decide on logging more later. I had thought about doing module name-based stuff too (coming from Java land where that's standard) but didn't bother with it here. Now that there's actually submodules, I think it's reasonable if we wanted to use it.

2022-11-21 23:57 UTC, ajyl commented on potato/flask_server.py
> +
If we remove the dependency between `logger` and `config`, we can certainly move everything related to `args` to `run_server()` and simply initialize `logger` as `getLogger(__name__)` at the module level, which I think might be the cleanest approach?

2022-11-21 23:59 UTC, ajyl commented on potato/server_utils/logger.py
> +    logger = logging.getLogger(logger_name)
My vote would be to break the dependency between `logger` and `config` and change all `loggers` to module-level loggers in this PR, breaking that dependency will likely make all future refactors easier in my opinion. See my [response](https://github.com/davidjurgens/potato/pull/16#discussion_r1028620862) to your other comment!

2022-11-22 03:01 UTC, davidjurgens commented on potato/flask_server.py
> +
sounds great! (see other comment too)

2022-11-22 03:01 UTC, davidjurgens commented on potato/server_utils/logger.py
> +    logger = logging.getLogger(logger_name)
Agreed. let's break the dependency and switch to module-level logging. That will probably work in our favor for end-users easy filtering out some detailed messages at the module level

2022-11-22 05:52 UTC, ajyl commented
Decoupled the logger from config per our discussion! I believe this is ready to be merged.

2022-11-22 16:48 UTC, davidjurgens approved these changes

2022-11-22 16:48 UTC, merged